### ISSUE TITLE
3. Adding core game objects - Typo

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Sushi-Neko-SpriteKit-Swift3#11]
"Drag in roll.png and place it in the center of the screen near the bottom. I would suggest around (0,160), set the Name to sushiBasePiece."

Based on the position in the image, I believe this should be (160, 160) for position. 

This is what (160, 160) looks like in my editor:

<img width="381" alt="screen shot 2017-06-10 at 6 10 41 pm" src="https://user-images.githubusercontent.com/14242863/27007430-2ba801b4-4e08-11e7-9ab6-5942788872d5.png">

**Comment by dionlarson** [comment]
Fixed
