### ISSUE TITLE
3. Adding core game objects - Formatting Error

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Sushi-Neko-SpriteKit-Swift3#12]
<img width="903" alt="screen shot 2017-06-10 at 6 13 40 pm" src="https://user-images.githubusercontent.com/14242863/27007437-93cc7a4a-4e08-11e7-821a-2b492990516e.png">

Just some broken code tags is tooks like.

**Comment by dionlarson** [comment]
Fixed
