### ISSUE TITLE
5. Building the core mechanic - Formatting Fix

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Sushi-Neko-SpriteKit-Swift3#17]
Looks like broken code tags: 
<img width="877" alt="screen shot 2017-06-10 at 6 34 20 pm" src="https://user-images.githubusercontent.com/14242863/27007541-7c36b924-4e0b-11e7-9f8b-b6c8c3186ba6.png">

**Comment by dionlarson** [comment]
Fixed
