### ISSUE TITLE
5. Building the core mechanic - Broken Formatting

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Sushi-Neko-SpriteKit-Swift3#18]
Looks like broken formatting tags. 
<img width="841" alt="screen shot 2017-06-10 at 6 41 18 pm" src="https://user-images.githubusercontent.com/14242863/27007582-76378cb4-4e0c-11e7-9233-67a52c7571da.png">

**Comment by dionlarson** [comment]
Fixed
