### ISSUE TITLE
5. Building the core mechanic - Missing Code Tags

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Sushi-Neko-SpriteKit-Swift3#20]
<img width="827" alt="screen shot 2017-06-10 at 6 44 58 pm" src="https://user-images.githubusercontent.com/14242863/27007603-f30d4364-4e0c-11e7-997c-5accc7bec95f.png">

**Comment by dionlarson** [comment]
Fixed
