### ISSUE TITLE
5. Building the core mechanic

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Sushi-Neko-SpriteKit-Swift3#31]
In "Improving the cycle" the line:

`if let firstPiece = sushiTower.first as! SushiPiece `

generates an error and will not compile, as sushiTower.first is already type `SushiPiece?`

I suspect this is a Swift 3 conversion issue.

**Comment by dionlarson** [comment]
Fixed in 9364912345925398e638e941eb1b4dbcbd09a8c1
