### ISSUE TITLE
5. Building the core mechanic

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Sushi-Neko-SpriteKit-Swift3#4]
The Touch control code snipped is improperly formatted.

**Comment by zontan** [comment]
In the Sushi tower section, the call to `addRandomPieces(1)` does not name the input variable and needs to be `addRandomPieces(total: 1)`

And below, in Improving the cycle, the code block is improperly formatted.

Same with the code block in Moving the tower.

**Comment by dionlarson** [comment]
Fixed
