### ISSUE TITLE
3. Adding core game objects

### ISSUE THREAD

**Issue by BrandonTroche** [MakeSchool-Tutorials/Sushi-Neko-SpriteKit-Swift3#6]
Repeat in the code.

<img width="802" alt="screen shot 2017-06-08 at 10 00 20 pm" src="https://user-images.githubusercontent.com/13054451/26957928-e6697b3c-4c95-11e7-9d7d-19d119611ec6.png">

**Comment by dionlarson** [comment]
Fixed
